---
name: "🐛 Bug report"
labels: bug
about: Create a bug report to help us improve
---

<!-- Describe the expected and actual behavior here. -->

## Steps to reproduce

<!-- Please clarify how to reproduce the issue. If it requires a special environment, please document it (e.g. browser, mobile phone) -->

## Possible Solution

<!-- If you have suggestions on a fix for the bug, please describe it here. -->
