usecase: "Continuous Delivery"
jumbotron:
  image: '/images/full-pipeline.jpg'
blog_tags:
  - cd
  - pipeline
  - cicd
articles:
-
  - https://jenkins.io/blog/2015/12/03/pipeline-as-code-with-multibranch-workflows-in-jenkins
  - "Multibranch Workflows in Jenkins"
plugins:
-
  - "https://wiki.jenkins.io/display/JENKINS/Pipeline+Plugin"
  - "Pipeline plugin"
  - "allows creating Pipeline scripts for defining build/test/deploy stages of a delivery pipeline"
-
  - 'https://wiki.jenkins.io/display/JENKINS/Pipeline+Utility+Steps+Plugin'
  - 'Pipeline Utility Steps plugin'
  - 'provides a number of addition, useful, steps to the Pipeline DSL'
-
  - "https://wiki.jenkins.io/display/JENKINS/Job+DSL+Plugin"
  - "Job DSL plugin"
  - "creates a DSL to orchestrate job creation"
